version: '3.4'

services:
  migrations:
    build:
      context: ../../
      dockerfile: templates/service/database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - IdentityServer_DB=DemoModule_Identity
      - DemoModule_DB=DemoModule_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
